// <auto-generated />
using System;
using CityBreaks.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityBreaks.Web.Migrations
{
    [DbContext(typeof(CityBreaksContext))]
    [Migration("20250608215419_AddDeletedAtToProperty")]
    partial class AddDeletedAtToProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CountryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            Name = "New York"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Los Angeles"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            Name = "Vancouver"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 4,
                            Name = "London"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 4,
                            Name = "Manchester"
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "BRA",
                            CountryName = "Brasil"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "USA",
                            CountryName = "Estados Unidos"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "CAN",
                            CountryName = "Canadá"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "GBR",
                            CountryName = "Reino Unido"
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CityId");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Apartamento Luxo Centro",
                            PricePerNight = 250.00m
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Name = "Hotel Copacabana Palace",
                            PricePerNight = 800.00m
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Name = "Studio Times Square",
                            PricePerNight = 350.00m
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            Name = "Casa de Praia Malibu",
                            PricePerNight = 1200.00m
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            Name = "Apto com Vista para o Mar",
                            PricePerNight = 300.00m
                        },
                        new
                        {
                            Id = 6,
                            CityId = 6,
                            Name = "Flat Próximo ao Big Ben",
                            PricePerNight = 400.00m
                        },
                        new
                        {
                            Id = 7,
                            CityId = 6,
                            Name = "Loft Moderno Shoreditch",
                            PricePerNight = 320.00m
                        },
                        new
                        {
                            Id = 8,
                            CityId = 7,
                            Name = "Casa de Férias Manchester",
                            PricePerNight = 180.00m
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.HasOne("CityBreaks.Web.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Property", b =>
                {
                    b.HasOne("CityBreaks.Web.Models.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
